version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - wvdashboard

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot -d aayushparmar.com --email aayush.02.parmar@gmail.com --agree-tos --non-interactive --quiet; sleep 12h; done'

  wvdashboard:
    build: .
    container_name: wvdashboard
    environment:
      - MODE=prod
    volumes:
      - .:/usr/src/app
      - ./certbot/conf/live/aayushparmar.com:/etc/letsencrypt/live/aayushparmar.com
    ports: "3000:3000"
    expose:
      - "3000"
    command: /bin/sh -c "npm install && node app.js"
